version: "3"
services:
       todo-app:
           container_name: todo-app
           image: abdul125/todo-app
           restart: always
           build: .
           ports:
             - "3000:3000"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'